### ISSUE TITLE
Windows Line Endings

### ISSUE THREAD

**Issue by Idzikowski-Casey** [UW-Macrostrat/corelle#2]
Error keeps appearing when I try to build.

`': No such file or directorycute 'sh`

Caused by a line ending issue between Windows and Mac OS (crlf vs lf). I believe the issue is that some files' line endings are changed to CRLF when cloned from Github on a windows computer. Then docker won't build it because the linux base needs LF line endings. Changes to the .gitattributes don't seem to be working right now. A short term solution can be using this on the git command line at the time of cloning a repository.

`git clone git@github.com:repositoryname.git --config core.autocrlf=input`

If I clone using the `--config core.autocrlf=input` it will build successfully.

**Comment by davenquinn** [comment]
We've fixed this, I think!
